---
abstract: 'A set of data structures with the same structure'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-NDS-Multiele
provides:
  Data::NDS::Multiele:
    file: lib/Data/NDS/Multiele.pm
    version: 3.12
requires:
  Data::NDS: 0
  Storable: 0
  YAML::Syck: 0
  perl: 5.001
resources:
  license: http://dev.perl.org/licenses/
version: 3.12
