---
name: Data-NDS-Multiele
version: 3.11
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
abstract: A set of data structures with the same structure
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::NDS: 0
  Storable: 0
  YAML::Syck: 0
  perl: 5.001
provides:
  Data::NDS::Multiele:
    file: lib/Data/NDS/Multiele.pm
    version: 3.11
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
